package ADO3;


import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Bruna
 */
public class Exercicio05 extends javax.swing.JFrame {
    private int winPC = 0;
    private int losePC = 0;
    private int winUser = 0;
    private int loseUser = 0;

    /**
     * Creates new form Exercicio05
     */
    public Exercicio05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pedra = new javax.swing.JRadioButton();
        papel = new javax.swing.JRadioButton();
        tesoura = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        buttonJogar = new javax.swing.JButton();
        panelPlacar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        placarUser = new javax.swing.JLabel();
        placarPC = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXERCÍCIO 05");

        buttonGroup1.add(pedra);
        pedra.setText("Pedra");

        buttonGroup1.add(papel);
        papel.setText("Papel");

        buttonGroup1.add(tesoura);
        tesoura.setText("Tesoura");

        jLabel1.setText("ESCOLHA:");

        buttonJogar.setText("Jogar");
        buttonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJogarActionPerformed(evt);
            }
        });

        panelPlacar.setBorder(javax.swing.BorderFactory.createTitledBorder("PLACAR"));

        jLabel2.setText("PC");

        jLabel3.setText("Você");

        jLabel4.setText("W | L");

        jLabel5.setText("W | L");

        placarUser.setText("0 | 0");

        placarPC.setText("0 | 0");

        javax.swing.GroupLayout panelPlacarLayout = new javax.swing.GroupLayout(panelPlacar);
        panelPlacar.setLayout(panelPlacarLayout);
        panelPlacarLayout.setHorizontalGroup(
            panelPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlacarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPlacarLayout.createSequentialGroup()
                        .addGroup(panelPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(placarUser))
                        .addGap(43, 43, 43)
                        .addGroup(panelPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placarPC)
                            .addComponent(jLabel2)))
                    .addGroup(panelPlacarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelPlacarLayout.setVerticalGroup(
            panelPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPlacarLayout.createSequentialGroup()
                .addGroup(panelPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPlacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(placarUser)
                    .addComponent(placarPC))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(papel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tesoura, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(buttonJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(panelPlacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(panelPlacar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pedra, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(papel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tesoura, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonJogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJogarActionPerformed
        boolean pcWin = false;
        boolean empate = false;

        Random sort = new Random();
        int pc = sort.nextInt(3);

        String jogUser = "";
        String jogPc = "";
        switch (pc) {
            case 0:
                jogPc = "Pedra";
                break;
            case 1:
                jogPc = "Papel";
                break;
            case 2:
                jogPc = "Tesoura";
                break;
        }

        /* 0 = pedra
          1 = papel
          2 = tesoura */
        //condições pra declarar o vencedor
        if (pedra.isSelected()) {
            jogUser = "Pedra";
            if (pc == 1) {
                pcWin = true;
            } else if (pc == 0) {
                empate = true;
            }
        } else if (papel.isSelected()) {
            jogUser = "Papel";
            if (pc == 2) {
                pcWin = true;
            } else if (pc == 1) {
                empate = true;
            }
        } else if (tesoura.isSelected()) {
            jogUser = "Tesoura";
            if (pc == 0) {
                pcWin = true;
            } else if (pc == 2) {
                empate = true;
            }
        }

        //mostra quem venceu
        if (empate) {
            JOptionPane.showMessageDialog(this, "EMPATE!\n\n"
                    + jogPc + " (pc) x " + jogUser + " (você)");
        } else if (pcWin) {
            winPC++;
            loseUser++;
            JOptionPane.showMessageDialog(this, "QUE PENA, PC VENCEU!\n\n"
                    + jogPc + " (pc) x " + jogUser + " (você)\n");
        } else {
            winUser++;
            losePC++;
            JOptionPane.showMessageDialog(this, "PARABÉNS, VOCÊ VENCEU!\n\n"
                    + jogPc + " (pc) x " + jogUser + " (você)\n");
        }

        //muda o placar
        placarUser.setText(winUser + " | " + loseUser);
        placarPC.setText(winPC + " | " + losePC);
    }//GEN-LAST:event_buttonJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercicio05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonJogar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelPlacar;
    private javax.swing.JRadioButton papel;
    private javax.swing.JRadioButton pedra;
    private javax.swing.JLabel placarPC;
    private javax.swing.JLabel placarUser;
    private javax.swing.JRadioButton tesoura;
    // End of variables declaration//GEN-END:variables
}
